# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d365bbef939c54ac71f70c25828d2f85262fb6e8c08a20b0d4b3b6e358ab3960b855078184b37d12b162c6d2f04f4a319aaac9f170d58fb660c71f2529fb6117

test:
  secret_key_base: 85fba0bd846667782521ce9550019d1a65600700dc44e30b3660e78aae1e34a45012f4063817ef6659770806d62ef2b1236f43df31fc6b6d837901e93d3273f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
